return {
  diagnostics = {
    BoldDebug = " ",
    BoldError = " ",
    BoldHint = " ",
    BoldInformation = " ",
    BoldQuestion = " ",
    BoldWarning = " ",
    Debug = " ",
    Error = " ",
    Hint = " ",
    Information = " ",
    Question = " ",
    Warning = " ",
    Trace = "✎ ",
  },

  documents = {
    File = " ",
    FileEmpty = " ",
    Files = " ",
    Folder = " ",
    FolderEmpty = " ",
    OpenFolder = " ",
    OpenFolderEmpty = " ",
    SymLink = " ",
    SymlinkFolder = " ",
    Import = " ",
  },

  git = {
    Add       = " ",
    Modified  = " ",
    Deleted   = " ",
    Rename    = " ",
    Untracked = "",
    Ignore    = " ",
    Unstaged  = " ",
    Staged    = " ",
    Conflict  = "",
    Git       = "󰊢 ",
    Branch    = " ",
    DiffAlt   = " ",
    Octoface  = " ",
    Repo      = " ",
    Tag       = " ",
    Unmerged  = "󰘬 ",
    Other     = "󰄱 ",
  },

  kind = {
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = "󰈏 ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = "󰊕 ",
    Interface = " ",
    Keyword = " ",
    Method = " ",
    Module = "",
    Operator = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },

  type = {
    Array = " ",
    Boolean = "⏻ ",
    Number = " ",
    Object = " ",
    String = " ",
  },

  ui = {
    Arrow                   = " ",
    ArrowCircleDown         = " ",
    ArrowCircleLeft         = " ",
    ArrowCircleRight        = " ",
    ArrowCircleUp           = " ",
    ---
    ArrowClosed             = " ",
    ArrowOpen               = " ",
    ChevronRight            = "",
    ---
    ChevronShortDown        = " ",
    ChevronShortLeft        = " ",
    ChevronShortRight       = " ",
    ChevronShortUp          = " ",
    ---
    TriangleShortArrowDown  = " ",
    TriangleShortArrowLeft  = " ",
    TriangleShortArrowRight = " ",
    TriangleShortArrowUp    = " ",
    ---
    BoldArrowDown           = " ",
    BoldArrowLeft           = " ",
    BoldArrowRight          = " ",
    BoldArrowUp             = " ",
    ---
    LineLeft                = "▏",
    BoldLineLeft            = "▎",
    LineMiddle              = "│",
    BoldLineMiddle          = "┃",
    BoldLineDashedMiddle    = "┋",
    ---
    DividerLeft             = "",
    DividerRight            = "",
    ---
    BoldDividerLeft         = "",
    BoldDividerRight        = "",
    ---
    PowerlineLeftRound      = "",
    PowerlineRightRound     = "",
    ---
    Circle                  = " ",
    CircleSmall             = "●",
    CircleSmallEmpty        = "○",
    DoubleChevronRight      = "»",
    SignIn                  = " ",
    SignOut                 = " ",
    Triangle                = "󰐊",
    ---
    BoldBookmark            = " ",
    BoldBug                 = " ",
    BoldCalendar            = " ",
    BoldChecked             = " ",
    BoldClose               = "",
    BoldComment             = " ",
    BoldFile                = " ",
    BoldFileEmpty           = " ",
    BoldFolder              = " ",
    BoldHistory             = " ",
    BoldLock                = " ",
    BoldNote                = " ",
    BoldPencil              = " ",
    BoldPlus                = " ",
    BoldTable               = " ",
    BookMark                = "",
    Bug                     = " ",
    Calendar                = " ",
    Checked                 = " ",
    Close                   = "󰅖",
    Comment                 = " ",
    File                    = " ",
    FileEmpty               = " ",
    Folder                  = " ",
    History                 = " ",
    Lock                    = " ",
    Note                    = " ",
    Pencil                  = "󰏫 ",
    Table                   = " ",

    NewFile                 = " ",
    Files                   = " ",
    FileSymLink             = " ",
    FindFile                = "󰈞",
    FindText                = "󰊄",

    FolderOpen              = " ",
    EmptyFolderOpen         = " ",
    FolderSymlink           = " ",

    Check                   = " ",
    CloudDownload           = " ",
    Collection              = " ",
    Command                 = " ",
    Corner                  = "└ ",
    DebugConsole            = " ",
    Download                = " ",
    Edge                    = "│ ",
    Electric                = " ",
    Ellipsis                = "",
    List                    = "",
    Minus                   = "‒ ",
    Sleep                   = "󰒲 ",
    Stacks                  = "",

    Bluetooth               = " ",
    Camera                  = " ",
    Clipboard               = " ",
    Code                    = " ",
    Color                   = " ",
    Dashboard               = " ",
    Database                = " ",
    Doom                    = "",
    Fire                    = " ",
    Firefox                 = " ",
    Forward                 = " ",
    Game                    = " ",
    Gear                    = " ",
    GitHub                  = " ",
    Heart                   = " ",
    Home                    = " ",
    Keyboard                = " ",
    Lightbulb               = "󰌵 ",
    Music                   = "󰝚 ",
    NeoVim                  = " ",
    Package                 = " ",
    Paint                   = " ",
    Pause                   = " ",
    Person                  = " ",
    Pin                     = " ",
    Play                    = " ",
    Plug                    = " ",
    Power                   = " ",
    Project                 = " ",
    Question                = " ",
    Reload                  = " ",
    Rocket                  = " ",
    Save                    = "󰆓 ",
    Scopes                  = "",
    SearchLeft              = " ",
    SearchRight             = " ",
    Separator               = "▊ ",
    Star                    = " ",
    Tab                     = "󰌒 ",
    Target                  = "󰀘 ",
    Telescope               = " ",
    Terminal                = " ",
    Test                    = " ",
    Text                    = " ",
    Time                    = " ",
    Trash                   = " ",
    Tree                    = "",
    Vim                     = " ",
    Watches                 = "󰂥",
    Wifi                    = " ",
    Windows                 = " ",
  },

  misc = {
    Robot = "󰚩 ",
    Squirrel = " ",
    Tag = " ",
    Watch = "",
    Smiley = " ",
    Package = " ",
    CircuitBoard = " ",
  },
}
